### ISSUE TITLE
"Python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-PBYBBm/wireless/

### ISSUE THREAD

**Issue by champsupertramp** [joshvillbrandt/wireless#29]
Hi,

I'm running Mac OSX 10.11.6

- Python 2.7.10
- pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)

I tried running this command: `sudo pip install wireless` 

But it triggers error:
```
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-PBYBBm/wireless/
```

```
Collecting wireless
  Downloading wireless-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    zip_safe flag not set; analyzing archive contents...

    Installed /private/tmp/easy_install-1BA5NL/flake8-3.5.0/pytest_runner-3.0-py2.7.egg
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    no previously-included directories found matching 'docs/build/'
    zip_safe flag not set; analyzing archive contents...

    Installed /private/tmp/pip-build-PBYBBm/wireless/flake8-3.5.0-py2.7.egg
    Searching for tox
    Reading https://pypi.python.org/simple/tox/
    Best match: tox 2.9.1
    Downloading https://pypi.python.org/packages/a7/36/e61f5263491a179311c4eaf40cf7c7bfd3aec9087687da25a1d900cc089a/tox-2.9.1.tar.gz#md5=7aa99d0eb206e4b070b9546115271cdb
    Processing tox-2.9.1.tar.gz
    Writing /tmp/easy_install-gGLIKo/tox-2.9.1/setup.cfg
    Running tox-2.9.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gGLIKo/tox-2.9.1/egg-dist-tmp-1I_1Y1
    Searching for setuptools-scm
    Reading https://pypi.python.org/simple/setuptools_scm/
    Best match: setuptools-scm 1.15.6
    Downloading https://pypi.python.org/packages/f2/4d/f79818ef2f6c129e81cc2d7622fa195fa4511457f1fb8140129f568bcf7c/setuptools_scm-1.15.6-py2.7.egg#md5=7eaa86e817a5d3f68aa69d77b4430bf3
    Processing setuptools_scm-1.15.6-py2.7.egg
    Moving setuptools_scm-1.15.6-py2.7.egg to /private/tmp/easy_install-gGLIKo/tox-2.9.1

    Installed /private/tmp/easy_install-gGLIKo/tox-2.9.1/setuptools_scm-1.15.6-py2.7.egg
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    warning: no files found matching 'CHANGELOG'
    zip_safe flag not set; analyzing archive contents...
    tox._pytestplugin: module references __file__
    tox.config: module references __file__
    tox.interpreters: module MAY be using inspect.getsource
    tox.session: module references __file__

    Installed /private/tmp/pip-build-PBYBBm/wireless/tox-2.9.1-py2.7.egg
    Searching for configparser
    Reading https://pypi.python.org/simple/configparser/
    Best match: configparser 3.5.0
    Downloading https://pypi.python.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz#md5=cfdd915a5b7a6c09917a64a573140538
    Processing configparser-3.5.0.tar.gz
    Writing /tmp/easy_install-wBpaK5/configparser-3.5.0/setup.cfg
    Running configparser-3.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wBpaK5/configparser-3.5.0/egg-dist-tmp-CHK75K

    Installed /private/tmp/pip-build-PBYBBm/wireless/configparser-3.5.0-py2.7.egg
    Searching for enum34
    Reading https://pypi.python.org/simple/enum34/
    Best match: enum34 1.1.6
    Downloading https://pypi.python.org/packages/e8/26/a6101edcf724453845c850281b96b89a10dac6bd98edebc82634fccce6a5/enum34-1.1.6.zip#md5=61ad7871532d4ce2d77fac2579237a9e
    Processing enum34-1.1.6.zip
    Writing /tmp/easy_install-Jxnyfg/enum34-1.1.6/setup.cfg
    Running enum34-1.1.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Jxnyfg/enum34-1.1.6/egg-dist-tmp-PcdJZW
    zip_safe flag not set; analyzing archive contents...

    Installed /private/tmp/pip-build-PBYBBm/wireless/enum34-1.1.6-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-PBYBBm/wireless/setup.py", line 33, in <module>
        zip_safe=False
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (setuptools 1.1.6 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('setuptools>=30'))

    ----------------------------------------

```

**Comment by 2600box** [comment]
after a year, i guess you figured it out, but your `setuptools` version is too old. you need to upgrade, but can't upgrade the system version becuase of SIP. i did it with `pip install --upgrade setuptools --user python`
