### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by XayOn** [joshvillbrandt/wireless#8]
Traceback (most recent call last):
  File "/home/xayon/.virtualenvs/smoothie/lib/python3.4/site-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/home/xayon/.virtualenvs/smoothie/lib/python3.4/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "./smoothie/plugins/interfaces.py", line 28, in interfaces
    return str(Interfaces())
  File "./smoothie/plugins/__init__.py", line 37, in __init__
    self.run()
  File "./smoothie/plugins/__init__.py", line 78, in run
    self.callback()
  File "./smoothie/plugins/interfaces.py", line 20, in callback
    ifaces = [a for a in Wireless().interfaces()
  File "/home/xayon/.virtualenvs/smoothie/lib/python3.4/site-packages/wireless/Wireless.py", line 21, in __init__
    self._driver_name = self._detectDriver()
  File "/home/xayon/.virtualenvs/smoothie/lib/python3.4/site-packages/wireless/Wireless.py", line 47, in _detectDriver
    if len(response) > 0 and 'not found' not in response:
TypeError: 'str' does not support the buffer interface

**Comment by XayOn** [comment]
You should probably add some real tests ;)
